name: Move Issue to To Do Column

on:
  project_card:
    types: [created]

jobs:
  move_to_todo:
    runs-on: ubuntu-latest

    steps:
      - name: Move issue to To Do column
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event.project_card.content_url }}" != "" ]; then
            PROJECT_URL="https://api.github.com/projects/columns"
            COLUMN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PROJECT_URL | jq '.[] | select(.name == "To Do").id')
            ISSUE_URL="${{ github.event.project_card.content_url }}"
            curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" $PROJECT_URL/cards -d "{\"column_id\": $COLUMN_ID, \"content_url\": \"$ISSUE_URL\"}"
          fi
